name: Deploy Static Website using Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Stop and remove old container if exists
        shell: powershell
        run: |
          $container = docker ps -a --format "{{.Names}}" | Select-String "^static-site$"
          if ($container) {
            docker stop static-site
            docker rm static-site
          } else {
            Write-Host "Container static-site does not exist. Skipping stop/remove."
          }

      - name: Remove old image if exists
        shell: powershell
        run: |
          $image = docker images -q static-web
          if ($image) {
            docker rmi static-web
          } else {
            Write-Host "Image static-web does not exist. Skipping remove."
          }

      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t static-web .

      - name: Run Docker container
        shell: powershell
        run: |
          docker run -d -p 8080:80 --name static-site static-web
